---
title: "PAINEL COVID-19"
author: "FAPESPA"
format:
  dashboard:
    orientation: rows
    theme: cosmo
    nav-buttons: [linkedin, snapchat, facebook]
---

###  {.sidebar}

Sidebar Content

```{r}
pacman::p_load(ggplot2, readxl, dygraphs, xts,
               htmlwidgets)



```

# Aba 1

## Row {height="20%"}

```{r}
#| content: valuebox
#| title: "Trimestre Anterior"
#| icon: pencil
#| color: #22396a
list(
  value = 20
)
```

```{r}
#| content: valuebox
#| title: "Acumulado"
list(
  icon = "chat",
  color = "#22396a",
  value = 50
)
```

```{r}
#| content: valuebox
#| title: "trimestre ano anterior"
list(
  icon = "trash",
  color = "danger",
  value = 40
)
```

```{r}
#| content: valuebox
#| title: "Trimestre Anterior/Brasil"
list(
  icon = "trash",
  color = "primary",
  value = 8736
)
```

```{r}
#| content: valuebox
#| title: "Acumulado/Brasil"
list(
  icon = "trash",
  color = "primary",
  value = 2021231
)
```

```{r}
#| content: valuebox
#| title: "Trimestre Ano Anterior/Brasil"
list(
  icon = "trash",
  color = "primary",
  value = 2021231
)
```

## Row {height="40%"}

### VBP

```{r}



```

### grafico1

```{r}



```

## Row {height="40%"}

### Plot 1

```{r}
knitr::kable(iris, align = "c")
```

### Plot2

```{r}
knitr::kable(iris, align = "c")
```

# 
